#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e

stack build :my-xmonad-exe --verbosity error
stack install :my-xmonad-exe --local-bin-path bin/ --verbosity error
mv bin/my-xmonad-exe "$1"
