resolver: lts-18.14

packages:
  - xmobar
  - xmonad
  - xmonad-contrib

extra-deps:
- X11-1.10
flags:
  xmobar:
    with_xft: true
    with_datezone: true
extra-package-dbs: []

ghc-options:
  "$everything": -haddock
