resolver: lts-17.15

packages:
  - xmobar
  - xmonad
  - xmonad-contrib

extra-deps:
- X11-1.9.2
flags:
  xmobar:
    with_xft: true
    with_datezone: true
extra-package-dbs: []

ghc-options:
  "$everything": -haddock
