resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/9.yaml

packages:
  - xmobar
  - xmonad
  - xmonad-contrib

extra-deps:
- X11-1.10
flags:
  xmobar:
    with_xft: true
    with_datezone: true
extra-package-dbs: []

ghc-options:
  "$everything": -haddock
