resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/0.yaml

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git

extra-deps:
flags:
extra-package-dbs: []
