[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''
[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
