[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo =  'scrooloose/syntastic'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'tfnico/vim-gradle'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set showmode
  set showcmd
  set ruler
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/groovyindent-unix'
on_ft = ['groovy']

[[plugins]]
repo= 'scrooloose/nerdtree'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
let g:gruvbox_italic=1
set background=dark
colorscheme gruvbox
let g:airline_theme = 'gruvbox'
'''

