[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
'''

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'tfnico/vim-gradle'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set showmode
  set showcmd
  set ruler
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'
