[[plugins]]
repo = 'Shougo/dein.vim'

# end補完
# https://github.com/tpope/vim-endwise
[[plugins]]
repo = 'tpope/vim-endwise'

# https://github.com/vim-syntastic/syntastic
# 構文エラーチェック
[[plugins]]
repo =  'scrooloose/syntastic'

# https://github.com/w0rp/ale
#[[plugins]]
#repo = 'w0rp/ale'

#https://github.com/tpope/vim-fugitive
# git rapper plugins
[[plugins]]
repo = 'tpope/vim-fugitive'

# A Vim plugin which shows a git diff in the sign column.
# https://github.com/airblade/vim-gitgutter
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 検索時にマッチした個数とそれが何番目であるかの情報を表示する
# https://github.com/osyo-manga/vim-anzu
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# シンタックスハイライト for kotlin
[[plugins]]
repo = 'udalov/kotlin-vim'

# シンタックスハイライト for gradle
[[plugins]]
repo = 'tfnico/vim-gradle'

# 行末スペースをハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# groovy indent script
# https://www.vim.org/scripts/script.php?script_id=5257
[[plugins]]
repo = 'vim-scripts/groovyindent-unix'
on_ft = ['groovy']

# When the plugin is correctly loaded, there will be a nice statusline at the bottom of each vim window.
# https://github.com/vim-airline/vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
'''
depends = ['vim-airline-themes']

#https://github.com/vim-airline/vim-airline-themes
#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#hook_add = '''
#'''

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
  set termguicolors
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  syntax enable
  colorscheme tender
  let g:airline_theme = 'tender'
'''

#ファイルの形式を文脈で判断するプラグイン
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_add = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# LSP client
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
source ~/.config/nvim/plugins/rust.rc.vim
let g:rustfmt_autosave = 1
nmap gg=G :rustfmt
'''

#LSP server
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

#[[plugins]]
#repo = 'ruby-formatter/rufo-vim'
#hook_add = '''
#let g:rufo_auto_formatting = 1
#'''
#[[plugins]]
#repo = 'neoclide/coc-css'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-html'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-python'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-yaml'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-json'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-vimtex'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-java'
#depends = 'coc.nvim'
#[[plugins]]
#repo = 'neoclide/coc-rls'
#depends = 'coc.nvim'

# toml lsp client
# https://www.npmjs.com/package/coc-toml
[[plugins]]
repo    = 'kkiyama117/coc-toml'
depends = 'coc.nvim'
on_ft   = 'toml'


[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   'rust': ['rustfmt'],
\}
let g:ale_rustfmt_executable = 'rustfmt'
'''
