[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1 " Remove this line if using the default palette.
set background=dark
colorscheme hybrid
'''

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'udalov/kotlin-vim'

[[plugins]]
repo = 'tfnico/vim-gradle'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  set laststatus=2
  set showmode
  set showcmd
  set ruler
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-scripts/groovyindent-unix'
on_ft = ['groovy']

[[plugins]]
repo= 'scrooloose/nerdtree'

[[plugins]]
repo= 'rust-lang/rust.vim'

[[plugins]]
repo = 'neovim/nvim-lsp'

